[32mINFO    [0m Login Test:test_login.py:22 Executing TC_3 with problem_user as username and vasca as password in cloud browser...
[32mINFO    [0m Login Test:test_login.py:25 Starting browser session...
[32mINFO    [0m Login Test:test_login.py:30 Entering login credentials...
[32mINFO    [0m Login Test:test_login.py:36 Validating login...
[31m[1mERROR   [0m Login Test:test_login.py:41 Epic sadface: Username and password do not match any user in this service
[32mINFO    [0m Login Test:test_login.py:44 Actual result matches the expected condition