--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 24, in test_shopping
    log.info("Executing "+ tc_id + " with " + xstr(name) + " as username and " + xstr(password) + " as password in "+ browserType +" browser..." )
Message: 'Executing TC_5 with error_user as username and secret_sauce as password in cloud browser...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 28, in test_shopping
    log.info("Starting browser session...")
Message: 'Starting browser session...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 32, in test_shopping
    log.info("Entering login credentials...")
Message: 'Entering login credentials...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 39, in test_shopping
    log.info("Validating login...")
Message: 'Validating login...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 42, in test_shopping
    log.info("Logged in successfully")
Message: 'Logged in successfully'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 45, in test_shopping
    log.info("Login Check performed successfully...")
Message: 'Login Check performed successfully...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 51, in test_shopping
    log.info("Adding required items to cart..")
Message: 'Adding required items to cart..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 57, in test_shopping
    log.info("Adding "+ item +" to cart..")
Message: 'Adding Test.allTheThings() T-Shirt (Red) to cart..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 57, in test_shopping
    log.info("Adding "+ item +" to cart..")
Message: 'Adding Sauce Labs Onesie to cart..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 60, in test_shopping
    log.info("Proceeding to cart..")
Message: 'Proceeding to cart..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 64, in test_shopping
    log.info("Removing "+ item +" from cart..")
Message: 'Removing  from cart..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 67, in test_shopping
    log.info("Checking if all the required items are added and removed as expected...")
Message: 'Checking if all the required items are added and removed as expected...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 73, in test_shopping
    log.info("Proceeding to checkout..")
Message: 'Proceeding to checkout..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 74, in test_shopping
    log.info("Entering form details..")
Message: 'Entering form details..'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 80, in test_shopping
    log.info("Completing the transaction...")
Message: 'Completing the transaction...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 95, in test_shopping
    log.error("Shopping is terminated...")
Message: 'Shopping is terminated...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 96, in test_shopping
    raise AssertionError("The expected outcome was not achieved")
AssertionError: The expected outcome was not achieved

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 98, in test_shopping
    log.error("The process did not complete as expected..."+ str(e))
Message: 'The process did not complete as expected...The expected outcome was not achieved'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 96, in test_shopping
    raise AssertionError("The expected outcome was not achieved")
AssertionError: The expected outcome was not achieved

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 99, in test_shopping
    pytest.fail(str(e))
    ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\outcomes.py", line 178, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: The expected outcome was not achieved

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 241, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: TResult | None = func()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Jarvis\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\Selenium Practices\Week 8\test_cases\test_shopping.py", line 104, in test_shopping
    log.info("Quitting the browser session...")
Message: 'Quitting the browser session...'
Arguments: ()
